# Dependencies
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true

permalink: pretty

source: '.'
destination: './_site'
encoding: UTF-8
exclude:
  - .git/
  - .github/
  - .idea/
  - src/
  - vendor
  - node_modules/
  - AUTHORS
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - package.json
  - package-lock.json
  - README.md
  - bootstrap/

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

toc:
  max_level: 3

# Social
title: 'Bootstrap Italia'
description: 'Bootstrap Italia Ã¨ un tema Bootstrap 5 per la creazione di applicazioni web nel pieno rispetto delle linee guida di design per i siti internet e i servizi digitali della PA'
authors: 'Dipartimento per la trasformazione digitale'
authors_url: 'https://innovazione.gov.it'
authors_agid: "Agenzia per l'Italia Digitale"
authors_agid_url: 'https://www.agid.gov.it/'
social_card_path: '/docs/assets/img/favicons/social-card.png'
social_logo_path: '/docs/assets/img/favicons/android-chrome-192x192.png'
repo: 'https://github.com/italia/bootstrap-italia/'
developers: 'https://developers.italia.it/'
slack: 'https://slack.developers.italia.it/'
twitter: 'https://twitter.com/designersITA'
twitter_handle: '@designersITA'

# Versions
current_version:		2.6.1
bootstrap_version: 5.2.3
bootstrap_minor: 5.1

# Analytics
wai_siteid: 'kjpRNRPp1y'

# CDN links
cdn:
  jquery: '<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" crossorigin="anonymous"></script>'
  popper: '<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js" crossorigin="anonymous"></script>'
  owlcarousel: '<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" crossorigin="anonymous"></script>'
