# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         "."
destination:    ./_gh_pages
baseurl:        "/bootstrap-italia"
url:            "/bootstrap-italia"
encoding:       UTF-8
exclude:
  - .git/
  - .github/
  - src/
  - public/
  - node_modules/
  - AUTHORS
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - package.js
  - package.json
  - package-lock.json
  - README.md
  - gulpfile.js

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

# Social
title:              "Bootstrap Italia"
description:        "Tema Bootstrap aderente alle linee guida per i servizi web delle Pubbliche Amministrazioni"
authors:            "Team per la Trasformazione Digitale"
authors_url:        "https://teamdigitale.governo.it/"
social_image_path:  "TODO"
social_logo_path:   "TODO"

# Custom variables
current_version:      0.3.0
bootstrap_version:    4
repo:                 "https://github.com/italia/bootstrap-italia/"
developers:           "https://developers.italia.it/"
slack:                "https://slack.developers.italia.it/"
twitter:              "https://twitter.com/teamdigitaleIT"

download:
  source:           "src/"
  dist:             "dist/"

cdn:
  css:              "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
  js:               "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
  jquery:           "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.slim.min.js"
  jquery_integrity: "sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g="
  popper:           "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js"
  popper_integrity: "sha256-pS96pU17yq+gVu4KBQJi38VpSuKN7otMrDQprzf/DWY="
