# Dependencies
markdown:       kramdown
highlighter:    rouge
kramdown:
  auto_ids:     true

permalink:      pretty

source:         "."
destination:    "./_site"
baseurl:        ""
url:            "http://localhost:4000"
encoding:       UTF-8
exclude:
  - .git/
  - .github/
  - .idea/
  - src/
  - vendor
  - node_modules/
  - AUTHORS
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - package.json
  - package-lock.json
  - README.md
  - gulpfile.js

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

toc:
  max_level: 3

# Social
title:              'Bootstrap Italia'
description:        'Bootstrap Italia Ã¨ un tema Bootstrap 4 per la creazione di applicazioni web nel pieno rispetto delle Linee guida di design per i servizi web della PA'
authors:            'Team per la Trasformazione Digitale'
authors_url:        'https://teamdigitale.governo.it/'
authors_agid:       "Agenzia per l'Italia Digitale"
authors_agid_url:   'https://www.agid.gov.it/'
social_card_path:   '/docs/assets/img/favicons/social-card.png'
social_logo_path:   '/docs/assets/img/favicons/android-chrome-192x192.png'
repo:               'https://github.com/italia/bootstrap-italia/'
developers:         'https://developers.italia.it/'
slack:              'https://slack.developers.italia.it/'
twitter:            'https://twitter.com/teamdigitaleIT'
twitter_handle:     '@teamdigitaleIT'

# Versions
current_version:		1.3.1
bootstrap_version:  4.3.1
bootstrap_minor:    4.3

# Analytics
ga_property:        'UA-114758441-1'

# CDN links
cdn:
  jquery:           '<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" crossorigin="anonymous"></script>'
  popper:           '<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" crossorigin="anonymous"></script>'
  owlcarousel:      '<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" crossorigin="anonymous"></script>'

