on: [push, pull_request]
jobs:
  container:
    runs-on: ubuntu-latest
    container: 
      image: timbru31/ruby-node:3.0-16
    steps:
      - uses: actions/checkout@v2.3.1
      - run: bundle install
      - run: npm i gulp -g
      - run: chmod -R 777 .
      - run: npm ci
      - run: npm run build